### ISSUE TITLE
I need higher version

### ISSUE THREAD

**Issue by nnothing1** [Subarashii-no-Fansub/AAE-Export#2]
I can't use it in blender 2.80,could you update it to 2.8x? thx

**Comment by Subarashii-no-Fansub** [comment]
@fxbjhc Thanks for reporting your issue.
Can you test my updated code (see the file from [here](https://raw.githubusercontent.com/Subarashii-no-Fansub/AAE-Export/d75f9a117fa7dae4dcd05723fbf8bc06805f6912/aae-export.py) or directly the PR #3) with blender 2.80?

Thanks

**Comment by nnothing1** [comment]
This code seems to work well, thank you for updating. This is a big help for me.
Thank you.
